spring:
  application:
    name: spring-clients
  cloud:
    kubernetes:
      discovery:
        enabled: true
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
